import sys

bytes = sys.stdin.buffer.read() # open("basic.bin","rb").read()

print("; XXX AUTOGENERATED XXX")

print("\tCSEG")
print("ORIG:\t")

for b in bytes:
  print("\tdb %03XH" % b)

print("\tEND\tORIG")
